[assembly: System.Reflection.AssemblyTitle("AutofacExtensions")]
[assembly: System.Reflection.AssemblyDescription("Extension methods for Autofac")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("7dd33ef3-56ec-4187-b870-5871a9efabe5")]
[assembly: System.CLSCompliant(true)]
